apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: auth
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: auth
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: gcr.io/s9-demo/gauther:latest
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "0.5"
              limits:
                memory: "1Gi"
                cpu: "1"
            env:
            - name: RELEASE
              value: "v0.4.9"
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gauther
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gauther
                  key: OAUTH_CLIENT_SECRET
            - name: GCP_PROJECT_ID
              value: "s9-demo"
            - name: EXTERNAL_URL
              value: "https://auth.demo.knative.tech"